// <auto-generated />
using System;
using ASPAssignment.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASPAssignment.Migrations
{
    [DbContext(typeof(ASPAssignmentContext))]
    partial class ASPAssignmentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASPAssignment.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account");

                    b.Property<string>("Address");

                    b.Property<string>("Name");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("ASPAssignment.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<int?>("CustomersCustomerId");

                    b.Property<string>("FoodType");

                    b.Property<int>("Name");

                    b.Property<double>("Price");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomersCustomerId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("ASPAssignment.Models.Order", b =>
                {
                    b.HasOne("ASPAssignment.Models.Customer", "Customers")
                        .WithMany("Orders")
                        .HasForeignKey("CustomersCustomerId");
                });
#pragma warning restore 612, 618
        }
    }
}
